<a href="https://colab.research.google.com/github/Car27VeP/Data_Science_Projects/blob/main/Limpieza_de_Datos_de_Ventas_Internacionales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠️ Reto: "Limpieza de Datos de Ventas Internacionales"
Imagina que recibes un reporte de ventas de una empresa con sede en Malta que vende productos en toda Europa. El archivo es un desastre: tiene símbolos de moneda, fechas mal formateadas, nombres con espacios extra y valores nulos.

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Fecha_Venta': ['2023-01-01', '02/01/2023', '2023-01-03', '2023-01-04', 'nan', '2023-01-06'],
    'ID_Producto': ['  PROD_01 ', 'PROD_02', 'prod_01', 'PROD_03', 'PROD_01', ' PROD_02 '],
    'Precio_Unitario': ['$150.00', '120,50€', '$150.00', 'nan', '150.00', '120.50'],
    'Cantidad': [1, 2, np.nan, 1, 5, 2],
    'Email_Cliente': ['CARLOS@mail.com', 'ana@MAIL.com', '  carlos@mail.com', 'pedro@gmail.com', 'info@tienda.com', 'ANA@mail.com']
}

df_dirty = pd.DataFrame(data)

In [ ]:
df_dirty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha_Venta      6 non-null      object
 1   ID_Producto      6 non-null      object
 2   Precio_Unitario  6 non-null      object
 3   Cantidad         5 non-null      float64
 4   Email_Cliente    6 non-null      object
dtypes: float64(1), object(4)
memory usage: 372.0+ bytes

In [ ]:
df_dirty.head()

  Fecha_Venta ID_Producto Precio_Unitario  Cantidad      Email_Cliente
0  2023-01-01    PROD_01          $150.00       1.0    CARLOS@mail.com
1  02/01/2023     PROD_02         120,50€       2.0       ana@MAIL.com
2  2023-01-03     prod_01         $150.00       NaN    carlos@mail.com
3  2023-01-04     PROD_03             nan       1.0    pedro@gmail.com
4         nan     PROD_01          150.00       5.0    info@tienda.com

In [ ]:
# Estandarizacion de texto
df_dirty['ID_Producto'] = df_dirty['ID_Producto'].str.strip().str.lower()
df_dirty['Email_Cliente'] = df_dirty['Email_Cliente'].str.strip().str.lower()

In [ ]:
df_dirty = df_dirty.drop_duplicates(subset=['ID_Producto','Email_Cliente'])

In [ ]:
df_dirty

  Fecha_Venta ID_Producto Precio_Unitario  Cantidad    Email_Cliente
0  2023-01-01     prod_01         $150.00       1.0  carlos@mail.com
1  02/01/2023     prod_02         120,50€       2.0     ana@mail.com
3  2023-01-04     prod_03             nan       1.0  pedro@gmail.com
4         nan     prod_01          150.00       5.0  info@tienda.com

In [ ]:
# Limpieza de monedas y conversión numérica
df_dirty['Precio_Unitario'] = df_dirty['Precio_Unitario'].str.replace('$','').str.replace('€','').str.replace(',','.')
df_dirty['Precio_Unitario'] = pd.to_numeric(df_dirty['Precio_Unitario'].replace('nan',np.nan))

In [ ]:
df_dirty['Precio_Unitario']

0    150.0
1    120.5
3      NaN
4    150.0
Name: Precio_Unitario, dtype: float64

In [ ]:
# Manejo de fechas y nulos
df_dirty['Fecha_Venta'] = pd.to_datetime(df_dirty['Fecha_Venta'],errors='coerce')
df_dirty['Precio_Unitario'] = df_dirty['Precio_Unitario'].fillna(df_dirty['Precio_Unitario'].median())

In [ ]:
df_dirty = df_dirty.dropna()

In [ ]:
df_dirty

  Fecha_Venta ID_Producto  Precio_Unitario  Cantidad    Email_Cliente
0  2023-01-01     prod_01            150.0       1.0  carlos@mail.com
3  2023-01-04     prod_03            150.0       1.0  pedro@gmail.com

In [ ]:
def col_gasto_total(data,col):
  data.loc[:, 'Gasto_Total'] = np.where(data[col] > 200,'Premium','Regular')
  return data

In [ ]:
df_dirty = col_gasto_total(df_dirty, 'Precio_Unitario')

In [ ]:
df_dirty

,Fecha_Venta,ID_Producto,Precio_Unitario,Cantidad,Email_Cliente,Gasto_Total
0,2023-01-01,prod_01,150.0,1.0,carlos@mail.com,Regular
3,2023-01-04,prod_03,150.0,1.0,pedro@gmail.com,Regular